
epochs: 20
seq_len: 256
batch_size: 44
num_workers: 4

d_model: 768
nhead: 12
lr: 0.02
warmup_updates: 1500
wd: 0.01
dropout: 0.1
xent_reduction: 'sum'

grad_accum: 1
clip_norm: 1.
valid_batch_size: 40

workd: 'exp/scaling-d-xent-reduction-higherlr'